### ISSUE TITLE
Невалиден линк към сайт

### ISSUE THREAD

**Issue by gkrastenov** [semerdzhiev/Reading-Lists#1]
В Algorithms.adoc в секцията Collections of Problems, Competitions, etc. 
линка към сайта http://judge.openfmi.net:9080/spoj0/ е невалиден

Предполагам, че правилинят линк трябва да бъде ->  https://judge.openfmi.net/

**Comment by semerdzhiev** [comment]
Благодаря за забележката. Вече е коригирано.
